version: "3.8"
services:
  laplacian_client:
    image: 'node:lts-bullseye'
    container_name: 'laplacian_client'
    volumes:
      - "./client:/client"
    working_dir: "/client"
    entrypoint: "/bin/bash -c"
    command:
      - "npm run dev"
    ports:
      - 3000:3000
    environment:
        API_URL: http://localhost:4000

  laplacian_api:
    image: 'node:lts-bullseye'
    container_name: 'laplacian_api'
    volumes:
      - ./api:/api
    working_dir: "/api"
    environment:
        DOMAIN_NAME: localhost
        PORT: 4000
        PROTOCOL: http
        CLIENT_URL: http://localhost:3000
        ANALYZER_URL: http://localhost:5000
        IMG_PATH: "./images/"
    entrypoint: "/bin/bash -c"
    command:
      - "npm start"
    ports:
      - 4000:4000
  laplacian_analyzer:
    image: 'alpine:latest'
    container_name: 'laplacian_analyzer'
    volumes:
      - ./analyzer:/analyzer
    working_dir: "/analyzer"
    environment:
        DOMAIN_NAME: localhost
        PORT: 5000
        PROTOCOL: http
        API_URL: http://localhost:4000
    entrypoint: "/bin/ash"
    # command:
    #   - "npm start"
    ports:
      - 5000:5000


# Create secrets with:
# printf "%s" "$(openssl rand -base64 20)" > mysql_password.secret
# printf "%s" "$(openssl rand -base64 20)" > mysql_root_password.secret
# printf "%s" "$(openssl rand -base64 10)" > server_token.secret

# TLS certificate has to be created manually and added as a secret
# openssl req -new -newkey rsa:4096 -x509 -sha256 -days 365 -nodes -out MyCertificate.crt -keyout MyKey.key

# Build with:
#   make install
# Launch with:
#   make up