version: "3.8"
services:
  laplacian_client:
    image: 'node:lts-bullseye'
    container_name: 'laplacian_client'
    volumes:
      - "./client:/client"
    working_dir: "/client"
    entrypoint: "/bin/bash -c"
    command:
      - "npm run dev"
    ports:
      - 3000:3000
    environment:
        API_URL: http://localhost:8080

  laplacian_analyzer:
    build: ./analyzer/
    container_name: 'laplacian_analyzer'
    volumes:
      - ./analyzer:/analyzer
    working_dir: "/analyzer"
    entrypoint: "/bin/bash -c"
    command:
      - "/usr/local/bin/laplacian"
    ports:
      - 8080:8080

# Build with:
#   make install
# Launch with:
#   make up